.TH Filter Designer 1 "March, 2017" Linux "User Manual"
.SH NAME:
filterdesigner \- A filter designer application
.SH SYNOPSIS:
.B filterdesigner [\-v \--version]
.SH DESCRIPTION:
.B filterdesigner
is a graphical design aid for the design of lowpass, highpass, and bandpass
filters. Passive and active topologies are supported.
.P
The project results are displayed in the main window, and may be saved to disk
and/or printed out. 
.P
.I See the on-line help for further information.
filterdesigner comes with detailed help documentation that is available
from either the toolbar or the main menu.
.SH OPTIONS:
.TP
\-v \--version: Show the version of the app on standard output, then exit.
.SH DIAGNOSTICS:
.B Filter Designer 
includes various message boxes and interactive dialogs to alert the
user to correctable, non-fatal errors. Other dialogs query for
confirmation before performing any action that could lose data. There
are also diagnostics printed to standard output that are viewable when starting
the app from a command line. These are mainly for debugging/developer maintenance.
.SH AUTHOR:
.B Filter Designer
was written by Simo. Developed with
the
.I FOX Toolkit
(http://www.fox-toolkit.org), and
.I XEMACS
(http://www.xemacs.org). Also debugged with 
.I Data Display Debugger
.SH REPORT BUGS:
Send bug reports to: simo@furrydolphin.net
.SH COPYRIGHT:
.B Filter Designer
is Copyright (C) 2017 by Simo. This program is free software.
See the on-line help for text of the GNU Public License.
